import 'package:equatable/equatable.dart';

// ─────────────────────────────────────────────
// WALLET SCREEN STATE
// ─────────────────────────────────────────────

/// Represents the current status of a payment process.
enum PaymentStatus {
  initial,
  loading,
  creatingOrder,
  orderCreated,
  success,
  failed
}

/// Represents the state of the WalletScreen.
class WalletState extends Equatable {
  /// The current payment status.
  final PaymentStatus paymentStatus;
  
  /// The amount pending to be paid.
  final double? pendingAmount;
  
  /// The unique order ID generated by the payment gateway.
  final String? orderId;
  
  /// A success message to be displayed to the user.
  final String? successMessage;
  
  /// An error message to be displayed to the user.
  final String? errorMessage;

  /// Helper to check if a loading action is currently taking place.
  bool get isLoading =>
      paymentStatus == PaymentStatus.loading ||
      paymentStatus == PaymentStatus.creatingOrder;
      
  /// Helper to check if the user can retry a payment.
  bool get canRetry => paymentStatus == PaymentStatus.failed;

  const WalletState({
    this.paymentStatus = PaymentStatus.initial,
    this.pendingAmount,
    this.orderId,
    this.successMessage,
    this.errorMessage,
  });

  /// Creates a copy of the current state with optionally updated fields.
  WalletState copyWith({
    PaymentStatus? paymentStatus,
    double? pendingAmount,
    String? orderId,
    String? successMessage,
    String? errorMessage,
  }) {
    return WalletState(
      paymentStatus: paymentStatus ?? this.paymentStatus,
      pendingAmount: pendingAmount ?? this.pendingAmount,
      orderId: orderId ?? this.orderId,
      successMessage: successMessage,
      errorMessage: errorMessage,
    );
  }

  @override
  List<Object?> get props => [
        paymentStatus,
        pendingAmount,
        orderId,
        successMessage,
        errorMessage,
      ];
}
