import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:food_delivery_app/main.dart' as app;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

    group('Food Delivery App User Flows', () {
        // We use a single testWidgets to avoid calling app.main() multiple times,
            // which would cause a duplicate Firebase App initialization error.
                testWidgets('Buyer and Seller E2E Flow', (WidgetTester tester) async {
                      // Launch the real app
                            app.main();
                                  await tester.pumpAndSettle(const Duration(seconds: 3));

                                        // --- 1. BUYER ONBOARDING ---
                                              final getStartedBtn = find.byKey(const ValueKey('onboardingNextButton'));
                                                    final getStartedBtnWeb = find.byKey(
                                                            const ValueKey('onboardingNextButton_web'),
                                                                  );

                                                                        if (getStartedBtn.evaluate().isNotEmpty) {
                                                                                await tester.tap(getStartedBtn.first);
                                                                                        await tester.pumpAndSettle();
                                                                                              } else if (getStartedBtnWeb.evaluate().isNotEmpty) {
                                                                                                      await tester.tap(getStartedBtnWeb.first);
                                                                                                              await tester.pumpAndSettle();
                                                                                                                    }

                                                                                                                          // --- 2. TRIGGER BUYER LOGIN ---
                                                                                                                                // Tapping the profile icon from Home Page to trigger Login Screen
                                                                                                                                      final profileIcon = find.byIcon(Icons.person_outline_rounded);
                                                                                                                                            if (profileIcon.evaluate().isNotEmpty) {
                                                                                                                                                    await tester.tap(profileIcon.first);
                                                                                                                                                            await tester.pumpAndSettle();
                                                                                                                                                                  } else {
                                                                                                                                                                          // Fallback: tap a food card to trigger login redirect
                                                                                                                                                                                  final textFind = find.textContaining('Pizza');
                                                                                                                                                                                          if (textFind.evaluate().isNotEmpty) {
                                                                                                                                                                                                    await tester.tap(textFind.first);
                                                                                                                                                                                                              await tester.pumpAndSettle();
                                                                                                                                                                                                                      }
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                  // --- 3. BUYER SIGNUP ---
                                                                                                                                                                                                                                        final signUpLink = find.byKey(const ValueKey('buyerSignupButton'));
                                                                                                                                                                                                                                              if (signUpLink.evaluate().isNotEmpty) {
                                                                                                                                                                                                                                                      await tester.tap(signUpLink);
                                                                                                                                                                                                                                                              await tester.pumpAndSettle();
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                          final uniqueEmail =
                                                                                                                                                                                                                                                                                    'buyer_${DateTime.now().millisecondsSinceEpoch}@example.com';
                                                                                                                                                                                                                                                                                          final nameField = find.widgetWithText(TextFormField, 'Enter Name');
                                                                                                                                                                                                                                                                                                final emailField = find.widgetWithText(TextFormField, 'Enter Email');
                                                                                                                                                                                                                                                                                                      final passwordField = find.widgetWithText(
                                                                                                                                                                                                                                                                                                              TextFormField,
                                                                                                                                                                                                                                                                                                                      'Enter Password',
                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                  final signUpButton = find.text('Sign Up');

                                                                                                                                                                                                                                                                                                                                        if (nameField.evaluate().isNotEmpty) {
                                                                                                                                                                                                                                                                                                                                                await tester.enterText(nameField, 'Test Buyer');
                                                                                                                                                                                                                                                                                                                                                        await tester.enterText(emailField, uniqueEmail);
                                                                                                                                                                                                                                                                                                                                                                await tester.enterText(passwordField, 'buyer123');
                                                                                                                                                                                                                                                                                                                                                                        await tester.pumpAndSettle();

                                                                                                                                                                                                                                                                                                                                                                                await tester.tap(signUpButton);
                                                                                                                                                                                                                                                                                                                                                                                        // Wait for Firebase Auth signup to complete and return to Login
                                                                                                                                                                                                                                                                                                                                                                                                await tester.pumpAndSettle(const Duration(seconds: 5));
                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                            // --- 4. BUYER LOGIN ---
                                                                                                                                                                                                                                                                                                                                                                                                                  final loginEmailField = find.byKey(
                                                                                                                                                                                                                                                                                                                                                                                                                          const ValueKey('buyerLoginEmailField'),
                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                      final loginPasswordField = find.byKey(
                                                                                                                                                                                                                                                                                                                                                                                                                                              const ValueKey('buyerLoginPasswordField'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                          final loginSubmitBtn = find.byKey(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const ValueKey('buyerLoginSubmitButton'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (loginEmailField.evaluate().isNotEmpty) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await tester.enterText(loginEmailField, uniqueEmail);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await tester.enterText(loginPasswordField, 'buyer123');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await tester.pumpAndSettle();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await tester.tap(loginSubmitBtn.first);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Wait for Firebase Auth login and navigation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await tester.pumpAndSettle(const Duration(seconds: 5));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // --- 5. NAVIGATE TO SELLER LOGIN ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // We are now authenticated. Open the profile drawer.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      final profileIconPostLogin = find.byIcon(Icons.person_outline_rounded);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (profileIconPostLogin.evaluate().isNotEmpty) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await tester.tap(profileIconPostLogin.first);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await tester.pumpAndSettle(const Duration(seconds: 2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Tap Seller Dashboard button in Drawer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              final sellerDashboardBtn = find.byKey(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const ValueKey('sellerLoginButton_Drawer'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (sellerDashboardBtn.evaluate().isNotEmpty) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await tester.tap(sellerDashboardBtn);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await tester.pumpAndSettle();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // --- 6. SELLER LOGIN ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    final sellerEmailField = find.byKey(const ValueKey('sellerEmailField'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          final sellerPasswordField = find.byKey(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const ValueKey('sellerPasswordField'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              final sellerSubmitBtn = find.byKey(const ValueKey('sellerSubmitButton'));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (sellerEmailField.evaluate().isNotEmpty) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await tester.enterText(sellerEmailField, 'seller@example.com');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await tester.enterText(sellerPasswordField, 'sellerpass123');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await tester.pumpAndSettle();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await tester.tap(sellerSubmitBtn.first);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await tester.pumpAndSettle(const Duration(seconds: 4));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // --- 7. SELLER ADD PRODUCT ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // We should now be on the Seller Add Product Screen
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    final productNameField = find.byKey(const ValueKey('productNameField'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          final productPriceField = find.byKey(const ValueKey('productPriceField'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                final productDescField = find.byKey(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const ValueKey('productDescriptionField'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    final productSubmitBtn = find.byKey(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const ValueKey('productSubmitButton'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (productNameField.evaluate().isNotEmpty) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await tester.enterText(productNameField, 'Test Integration Burger');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await tester.enterText(productPriceField, '12.99');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await tester.enterText(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          productDescField,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'A delicious test burger from integration tests',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await tester.pumpAndSettle();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Note: For image picking, the system native image picker dialog opens, which we can't interact with easily via Flutter driver.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // We will skip testing the actual image picking natively.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // If the submit requires an image, it will show a snackbar 'Please select an image first'.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // For the sake of UI navigation, we just attempt to submit.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await tester.tap(productSubmitBtn);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await tester.pumpAndSettle(const Duration(seconds: 2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // At this point, the seller should be logged in and the form filled.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      