class DeliveryNotificationStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'title': 'Notifications',
      'subtitle': 'Real-time order, earnings, account and chat updates',
      'all': 'All',
      'order': 'Orders',
      'earnings': 'Earnings',
      'account': 'Account',
      'chat': 'Chat',
      'unreadOnly': 'Unread Only',
      'markAllAsRead': 'Mark all as read',
      'clearAll': 'Clear all',
      'searchHint': 'Search notifications...',
      'emptyTitle': 'No Notifications',
      'emptySub': 'You are all caught up! New alerts will appear here in real-time.',
      'errorTitle': 'Failed to load notifications',
      'retry': 'Retry',
      'viewOrder': 'View Order',
      'viewWallet': 'View Wallet',
      'viewProfile': 'View Profile',
      'openChat': 'Open Chat',
      'newDeliveryRequest': 'New Delivery Request',
      'orderAssigned': 'Order Assigned',
      'orderCancelled': 'Order Cancelled',
      'pickupReminder': 'Pickup Reminder',
      'deliveryReminder': 'Delivery Reminder',
      'paymentAdded': 'Payment Added',
      'bonus': 'Bonus Reward',
      'incentive': 'Incentive Earned',
      'withdrawalSuccess': 'Withdrawal Successful',
      'verificationApproved': 'Verification Approved',
      'verificationRejected': 'Verification Rejected',
      'accountStatus': 'Account Status Update',
      'newMessage': 'New Chat Message',
      'justNow': 'Just now',
      'minutesAgo': '{minutes}m ago',
      'hoursAgo': '{hours}h ago',
      'daysAgo': '{days}d ago',
      'unreadBadge': '{count} New',
      'markedAsRead': 'Notification marked as read',
      'deletedNotification': 'Notification removed',
      'clearedAll': 'All notifications cleared',
    },
    'ta': {
      'title': 'அறிவிப்புகள்',
      'subtitle': 'நிகழ்நேர ஆர்டர், வருவாய், கணக்கு மற்றும் அரட்டை புதுப்பிப்புகள்',
      'all': 'அனைத்தும்',
      'order': 'ஆர்டர்கள்',
      'earnings': 'வருவாய்',
      'account': 'கணக்கு',
      'chat': 'அரட்டை',
      'unreadOnly': 'படிக்காதவை மட்டும்',
      'markAllAsRead': 'அனைத்தையும் படித்ததாகக் குறிக்கவும்',
      'clearAll': 'அனைத்தையும் அழிக்கவும்',
      'searchHint': 'அறிவிப்புகளைத் தேடுங்கள்...',
      'emptyTitle': 'அறிவிப்புகள் எதுவும் இல்லை',
      'emptySub': 'எல்லாம் புதுப்பித்த நிலையில் உள்ளது! புதிய எச்சரிக்கைகள் நிகழ்நேரத்தில் தோன்றும்.',
      'errorTitle': 'அறிவிப்புகளை ஏற்றுவதில் தோல்வி',
      'retry': 'மீண்டும் முயற்சிக்கவும்',
      'viewOrder': 'ஆர்டரைப் பார்க்கவும்',
      'viewWallet': 'வாலட்டைப் பார்க்கவும்',
      'viewProfile': 'சுயவிவரத்தைப் பார்க்கவும்',
      'openChat': 'அரட்டையைத் திறக்கவும்',
      'newDeliveryRequest': 'புதிய டெலிவரி கோரிக்கை',
      'orderAssigned': 'ஆர்டர் ஒதுக்கப்பட்டது',
      'orderCancelled': 'ஆர்டர் ரத்து செய்யப்பட்டது',
      'pickupReminder': 'பிக்கப் நினைவூட்டல்',
      'deliveryReminder': 'டெலிவரி நினைவூட்டல்',
      'paymentAdded': 'பணம் சேர்க்கப்பட்டது',
      'bonus': 'போனஸ் வெகுமதி',
      'incentive': 'ஊக்கத்தொகை பெறப்பட்டது',
      'withdrawalSuccess': 'பணம் எடுப்பது வெற்றிகரமானது',
      'verificationApproved': 'சரிபார்ப்பு அங்கீகரிக்கப்பட்டது',
      'verificationRejected': 'சரிபார்ப்பு நிராகரிக்கப்பட்டது',
      'accountStatus': 'கணக்கு நிலை புதுப்பிப்பு',
      'newMessage': 'புதிய அரட்டை செய்தி',
      'justNow': 'சற்று முன்',
      'minutesAgo': '{minutes} நிமிடம் முன்',
      'hoursAgo': '{hours} மணி நேரம் முன்',
      'daysAgo': '{days} நாள் முன்',
      'unreadBadge': '{count} புதியவை',
      'markedAsRead': 'படித்ததாக குறிக்கப்பட்டது',
      'deletedNotification': 'அறிவிப்பு அகற்றப்பட்டது',
      'clearedAll': 'அனைத்து அறிவிப்புகளும் அழிக்கப்பட்டன',
    },
  };

  static String of(String key, String localeCode) {
    final localeMap = _strings[localeCode] ?? _strings['en']!;
    return localeMap[key] ?? _strings['en']![key] ?? key;
  }
}
