// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2p5qPkTyj2zl3hxVvH1C5B-mN9vOXFs',
    appId: '1:318384112771:web:ad7285a79beb303b4d47b6',
    messagingSenderId: '318384112771',
    projectId: 'food-delivery-app-cd4ca',
    authDomain: 'food-delivery-app-cd4ca.firebaseapp.com',
    storageBucket: 'food-delivery-app-cd4ca.firebasestorage.app',
    measurementId: 'G-1CKZMSMETQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwTsgY7b5lSrYZVR7KX76Fkq4ijzZkBrA',
    appId: '1:318384112771:android:11050db862ada7e84d47b6',
    messagingSenderId: '318384112771',
    projectId: 'food-delivery-app-cd4ca',
    storageBucket: 'food-delivery-app-cd4ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUe9GxPkMwKvkPjw-zqGD5-VGGiDKD2Uw',
    appId: '1:318384112771:ios:6115d6bd6cd590624d47b6',
    messagingSenderId: '318384112771',
    projectId: 'food-delivery-app-cd4ca',
    storageBucket: 'food-delivery-app-cd4ca.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUe9GxPkMwKvkPjw-zqGD5-VGGiDKD2Uw',
    appId: '1:318384112771:ios:6115d6bd6cd590624d47b6',
    messagingSenderId: '318384112771',
    projectId: 'food-delivery-app-cd4ca',
    storageBucket: 'food-delivery-app-cd4ca.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo2p5qPkTyj2zl3hxVvH1C5B-mN9vOXFs',
    appId: '1:318384112771:web:16ce0266b612c6954d47b6',
    messagingSenderId: '318384112771',
    projectId: 'food-delivery-app-cd4ca',
    authDomain: 'food-delivery-app-cd4ca.firebaseapp.com',
    storageBucket: 'food-delivery-app-cd4ca.firebasestorage.app',
    measurementId: 'G-G1VC61MGJJ',
  );
}
