import 'package:food_delivery_app/features/Delivery%20Partner%20Bloc%20Architecture/Delivery_Orders_page/Delivery_Orders_page_state.dart';

/// Standard demo order used across delivery partner tests.
DeliveryOrderCardModel buildOrder({
  required String id,
  String customerName = 'Aarav Sharma',
  String restaurantName = 'Green Bowl Kitchen',
  String pickupAddress = 'MG Road, Bengaluru',
  String deliveryAddress = 'Koramangala, Bengaluru',
  double amount = 450.0,
  int itemsCount = 3,
  DeliveryOrderStatus status = DeliveryOrderStatus.pending,
  double distance = 4.2,
  String time = '10:30 AM',
  String paymentType = 'Cash',
  String phoneNumber = '+91 9876543210',
  int etaMins = 25,
  int preparationTimeMins = 15,
}) {
  return DeliveryOrderCardModel(
    orderId: id,
    customerName: customerName,
    restaurantName: restaurantName,
    pickupAddress: pickupAddress,
    deliveryAddress: deliveryAddress,
    amount: amount,
    itemsCount: itemsCount,
    status: status,
    distance: distance,
    time: time,
    paymentType: paymentType,
    phoneNumber: phoneNumber,
    etaMins: etaMins,
    preparationTimeMins: preparationTimeMins,
  );
}

/// Default demo order list used across delivery partner tests.
List<DeliveryOrderCardModel> demoOrders() => [
      buildOrder(
        id: 'ORD12345',
        customerName: 'Rohan Mehta',
        restaurantName: 'Green Bowl Kitchen',
        pickupAddress: '12th Main, Indiranagar',
        deliveryAddress: '80 Feet Road, Koramangala',
        amount: 480.0,
        itemsCount: 3,
        status: DeliveryOrderStatus.pending,
        distance: 3.4,
        time: '10:30 AM',
        paymentType: 'Cash',
        phoneNumber: '+91 9876543210',
        etaMins: 25,
        preparationTimeMins: 15,
      ),
      buildOrder(
        id: 'ORD12347',
        customerName: 'Vikram Singh',
        restaurantName: 'Spice Route',
        pickupAddress: 'Church Street, CBD',
        deliveryAddress: 'Jayanagar, Bengaluru',
        amount: 350.0,
        itemsCount: 2,
        status: DeliveryOrderStatus.active,
        distance: 2.2,
        time: '11:45 AM',
        paymentType: 'Online',
        phoneNumber: '+91 7654321098',
        etaMins: 12,
        preparationTimeMins: 8,
      ),
      buildOrder(
        id: 'ORD12346',
        customerName: 'Priya Nair',
        restaurantName: 'Tandoor Palace',
        pickupAddress: 'Church Street, CBD',
        deliveryAddress: 'HSR Layout, Bengaluru',
        amount: 620.0,
        itemsCount: 4,
        status: DeliveryOrderStatus.active,
        distance: 5.1,
        time: '11:15 AM',
        paymentType: 'Card',
        phoneNumber: '+91 8765432109',
        etaMins: 18,
        preparationTimeMins: 10,
      ),
      buildOrder(
        id: 'ORD12352',
        customerName: 'Sneha Iyer',
        restaurantName: 'Biryani House',
        pickupAddress: 'Residency Road',
        deliveryAddress: 'Whitefield, Bengaluru',
        amount: 520.0,
        itemsCount: 5,
        status: DeliveryOrderStatus.pending,
        distance: 6.7,
        time: '12:05 PM',
        paymentType: 'Cash',
        phoneNumber: '+91 6543210987',
        etaMins: 30,
        preparationTimeMins: 20,
      ),
    ];